apiVersion: apps/v1
kind: Deployment
metadata:
    name: complete-prodcution-e2e-deployment
spec:
    selector:
        matchLabels:
            app: complete-prodcution-e2e-app
    template:
        metadata:
            labels:
                app: complete-prodcution-e2e-app
        spec:
            containers:
                - name: complete-prodcution-e2e-app
                  image: maverick0809/complete-prodcution-e2e-pipeline:1.51.1
                  resources:
                      limits:
                          memory: '256Mi'
                          cpu: '500m'
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: complete-prodcution-e2e-svc
spec:
    type: NodePort
    selector:
        app: complete-prodcution-e2e-app
    ports:
        - port: 80
          targetPort: 8080
